### ISSUE TITLE
Kept being signed out on VSCode close

### ISSUE THREAD

**Issue by cig0** [vsls-contrib/communities#53]
Hi,

I kept being signed out from Live Share Communities every time I close VSCode.

VSCode: 1.37
OS: macOS 10.14.6 / NixOS 19.03

**Comment by lostintangent** [comment]
@cig0 Thanks for reporting this! I just pushed a fix for this issue and will deploy it to the marketplace in the morning.

**Comment by lostintangent** [comment]
This should now be fixed if you update to the latest marketplace version. Let me know if that isn't the case. Thanks!
