### ISSUE TITLE
Community chat date is wrong

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/communities#82]
I created data community this morning and expected the `Joined the community` message to show today's day: Wednesday, September 4. Instead it posted as Tuesday, September 3.

I am not sure what this would happen since I had live share disabled for some time and just enabled the whole ext. pack this morning to check out new communities addition. 

![vsls-data-community](https://user-images.githubusercontent.com/656833/64265782-1e2db000-cef9-11e9-8e1d-00b8603e02eb.png)

P.S.: I like the nice touch of whoever started new community becomes the Founder :)

**Comment by RandomFractals** [comment]
same thing when joining powershell community. I did not know I am living in the past, 1 day behind, till now :)

![vsls-powershell-community-joined](https://user-images.githubusercontent.com/656833/64270941-07d82200-cf02-11e9-9023-e089abeb180b.png)

**Comment by arjun27** [comment]
Thanks for catching this @RandomFractals. This is now fixed in https://github.com/vsls-contrib/chat/commit/8ea618fcf562c861aac58c72957b75fddb1cde9e
