### ISSUE TITLE
Let founder(s) set brief greeting message for new members joining

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/communities#88]
Community chat should then automatically send that message to welcome new members.

Posibly duplicate of or related to #44 & #54

here is a pic for this use case, although I suspect community founders might want to share longer greeting message with a link to rules of conduct, etc.

![vsls-community-onboarding-message](https://user-images.githubusercontent.com/656833/64345687-665ed800-cfb6-11e9-81e6-3b9675adadd5.png)

**Comment by arjun27** [comment]
Thanks @RandomFractals. You're right, this will be covered by #44. Would love to share an early preview of that with you to get your thoughts.

Closing this in favor of #44

**Comment by RandomFractals** [comment]
@arjun27 sounds good. keep in mind tho what I am suggesting here is setting/sending auto-response welcome message for new member joined, not just pinning a message in community panel.

I am available for early previews if you find my feedback constructive so far.

**Comment by RandomFractals** [comment]
@arjun27 actually, I think you should reopen this ticket. Hitting readme.md for a new dev space channel is not the same as sending a dev a greeting for joining it. thanks!
